<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 5</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d0cfe7a3482e0d49a74229a8f3b76718.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 5</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="task-1-querying-an-api-and-a-tidy-style-function" class="level2">
<h2 class="anchored" data-anchor-id="task-1-querying-an-api-and-a-tidy-style-function">Task 1: Querying an API and a Tidy-Style Function</h2>
<p>For this section, we connect to the news API here: newsapi.org.</p>
<ol type="1">
<li>We use <code>GET()</code> from the <code>httr</code> package to return information about the Strait of Hormuz and store the result as an R object. We can only look 30 days into the past because of the free account restiction.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading in needed packages </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'jsonlite' was built under R version 4.3.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># masking API</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>api_key <span class="ot">&lt;-</span> <span class="fu">Sys.getenv</span>(<span class="st">"NEWS_API_KEY"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (api_key <span class="sc">==</span> <span class="st">""</span>) {</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"NEWS_API_KEY has not been set."</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making sure we are within 30 days</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>from_date <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">Sys.Date</span>() <span class="sc">-</span> <span class="dv">29</span>, <span class="st">"%Y-%m-%d"</span>) </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"https://newsapi.org/v2/everything?q=Strait%20of%20Hormuz"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>              <span class="st">"&amp;from="</span>, from_date,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>              <span class="st">"&amp;language=en&amp;pageSize=50&amp;apiKey="</span>, <span class="fu">Sys.getenv</span>(<span class="st">"NEWS_API_KEY"</span>))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>news_result <span class="ot">&lt;-</span> <span class="fu">GET</span>(url)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>news_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response [https://newsapi.org/v2/everything?q=Strait%20of%20Hormuz&amp;from=2026-08-23&amp;language=en&amp;pageSize=50&amp;apiKey=6425018d9c264a2eb83d0a327b87dea2]
  Date: 2026-09-22 02:07
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 43.3 kB</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">content</span>(news_result, <span class="st">"text"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "{\"status\":\"ok\",\"totalResults\":6450,\"articles\":[{\"source\":{\"id\":\"bbc-news\",\"name\":\"BBC News\"},\"author\":\"https://www.facebook.com/bbcnews\",\"title\":\"Saudi Arabia shuts key oil pipeline after drone attack launched from Iraq\",\"description\":\"The East-West pipeline has helped the country - the world's largest crude oil exporter - bypass closures in the Strait of Hormuz.\",\"url\":\"https://www.bbc.co.uk/news/articles/c62m933465eo\",\"urlToImage\":\"https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/1ea8/live/13141950-ae5a-11f1-96a4-f736214d52e1.jpg\",\"publishedAt\":\"2026-09-12T04:43:10Z\",\"content\":\"Saudi Arabia has closed a critical oil pipeline after it was attacked by drones launched from Iraq, as conflict in the Middle East widens.\\r\\nIraq said it had fired a military commander and launched an… [+1613 chars]\"},{\"source\":{\"id\":\"bbc-news\",\"name\":\"BBC News\"},\"author\":\"https://www.facebook.com/bbcnews\",\"title\":\"US launches more strikes on Iran as state media reports explosions\",\"description\":\"US Central Command accused Iran of targeting commercial shipping and American service members deployed in the region.\",\"url\":\"https://www.bbc.co.uk/news/articles/cj06q4ynpmjo\",\"urlToImage\":\"https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/913b/live/5a3308c0-a629-11f1-a291-b542ee92de7c.jpg\",\"publishedAt\":\"2026-09-01T17:35:14Z\",\"content\":\"American forces resumed strikes against Iran on Tuesday, US Central Command said in a statement.\\r\\nIt accused the Islamic Revolutionary Guard Corps (IRGC) of \\\"recent attempted attacks\\\" against commerc… [+623 chars]\"},{\"source\":{\"id\":null,\"name\":\"Gizmodo.com\"},\"author\":\"Matt Novak\",\"title\":\"Trump Flips Out on Truth Social as Fed Hikes Interest Rates\",\"description\":\"Trump says the U.S. should stop trading with most other countries in the world.\",\"url\":\"https://gizmodo.com/trump-flips-out-on-truth-social-as-fed-hikes-interest-rates-2000812756\",\"urlToImage\":\"https://gizmodo.com/app/uploads/2026/09/kevin-warsh-2026-1200x675.jpg\",\"publishedAt\":\"2026-09-16T21:09:20Z\",\"content\":\"The Federal Reserve announced an interest rate hike of 0.25 percentage points Wednesday as a way to battle inflation. The question remains whether the move is actually able to make a dent since it’s … [+4581 chars]\"},{\"source\":{\"id\":\"business-insider\",\"name\":\"Business Insider\"},\"author\":\"Jake Epstein,Chris Panella\",\"title\":\"Iran says it captured an 'advanced' American underwater drone. The US says it was older, malfunctioning, and ‘dead in the water.’\",\"description\":\"A spokesperson for US Central Command said the underwater drone had malfunctioned before Iran claimed to have seized it near the Strait of Hormuz.\",\"url\":\"https://www.businessinsider.com/iran-found-us-naval-drone-us-says-dead-in-water-2026-9#article\",\"urlToImage\":\"https://i.insider.com/6aa064779b8974787b1c9972?width=1200&amp;format=jpeg\",\"publishedAt\":\"2026-09-08T20:24:06Z\",\"content\":\"US Central Command said the drone had malfunctioned \\\"well before\\\" it was seized by Iran.US Central Command Photo\\r\\n&lt;ul&gt;&lt;li&gt;Iran said it captured a US underwater drone near the Strait of Hormuz.&lt;/li&gt;&lt;l… [+2838 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Florence Tan\",\"title\":\"Two tankers carrying Saudi oil attacked in Strait of Hormuz\",\"description\":\"By Florence Tan SINGAPORE, Sept 1 (Reuters) - Two supertankers carrying Saudi oil were struck by unknown projectiles within minutes of each other while trans...\",\"url\":\"https://www.yahoo.com/news/world/articles/two-tankers-carrying-saudi-oil-102129723.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/47cbda8bf990a5006ef481f0e0de50704158107ae68603167ac5d425d2e17825/lightyear_networkapi/resizefill_w800_h507%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F0516247919d74122bd83dec20f3a23fe.jpg\",\"publishedAt\":\"2026-09-01T10:21:29Z\",\"content\":\"By Florence Tan\\r\\nSINGAPORE, Sept 1 (Reuters) - Two supertankers carrying Saudi oil were struck by unknown projectiles within minutes of each other while transiting outbound through the Strait of Horm… [+1956 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Elwely Elwelly and Enas Alashray\",\"title\":\"Iran war diplomacy turns toward reopening Strait of Hormuz\",\"description\":\"DUBAI/CAIRO, Aug 28 (Reuters) - Iran war mediators have placed renewed emphasis on reopening the Strait of Hormuz, with Tehran agreeing to draw up a list of...\",\"url\":\"https://www.yahoo.com/news/world/articles/iran-war-diplomacy-turns-toward-013400780.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/4b1d066092ccf34069d42706a618b7ee8081aeb6e575c4ac245d364aeb8c7e7a/lightyear_networkapi/resizefill_w800_h533%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F767fcd07016420110a15df4b35ce2d94.jpg\",\"publishedAt\":\"2026-08-28T01:44:54Z\",\"content\":\"By Elwely Elwelly and Enas Alashray\\r\\nDUBAI/CAIRO, Aug 28 (Reuters) - Iran war mediators have placed renewed emphasis on reopening the Strait of Hormuz, with Tehran agreeing to draw up a list of condi… [+3734 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":null,\"title\":\"Shipping traffic through Strait of Hormuz rises slightly, data shows\",\"description\":null,\"url\":\"https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_474a91a9-c24e-4bb4-8e55-e1341d42e53e\",\"urlToImage\":null,\"publishedAt\":\"2026-08-27T03:39:03Z\",\"content\":\"If you click 'Accept all', we and our partners, including 251 who are part of the IAB Transparency &amp;amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]\"},{\"source\":{\"id\":\"bbc-news\",\"name\":\"BBC News\"},\"author\":\"https://www.facebook.com/bbcnews\",\"title\":\"Lightning Houthi advance in Yemen may bring dangerous new dimension to Iran war\",\"description\":\"The capture by the rebels of a stretch Yemen's strategic coastline is the group's most impressive military coup for several years.\",\"url\":\"https://www.bbc.co.uk/news/articles/c3v4zgzr1kxo\",\"urlToImage\":\"https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/82b5/live/066e1ff0-ae16-11f1-aa28-67f8824e7b72.jpg\",\"publishedAt\":\"2026-09-11T19:44:58Z\",\"content\":\"\\\"Now that they are there, they're going to be entrenched,\\\" Hisham al-Omeisi, senior analyst at the Brussels-based European Institute of Peace, told the BBC. \\\"And it's going to be a lot more costly to… [+1238 chars]\"},{\"source\":{\"id\":null,\"name\":\"NPR\"},\"author\":\"Jane Arraf\",\"title\":\"Attacks flare between U.S., Iran after month-long pause\",\"description\":\"U.S. threats erupt into attacks in the Strait of Hormuz; Iran retaliates against U.S. targets in the UAE and Jordan in the first exchange of fire since July 29\",\"url\":\"https://www.npr.org/2026/08/31/g-s1-141175/attacks-flare-us-iran\",\"urlToImage\":\"https://npr.brightspotcdn.com/dims3/default/strip/false/crop/6000x3375+0+313/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F29%2Ffd%2F5217d77844848219593a4f0b61ba%2Fap26243261413105.jpg\",\"publishedAt\":\"2026-08-31T10:04:30Z\",\"content\":\"AMMAN, Jordan - The U.S. military struck what it said were Iranian rocket launchers in the Strait of Hormuz on Sunday while Iran retaliated with strikes on U.S. forces in Jordan and the United Arab E… [+3727 chars]\"},{\"source\":{\"id\":null,\"name\":\"Gizmodo.com\"},\"author\":\"Tom McKay\",\"title\":\"Say Hello To $6 Diesel\",\"description\":\"Diesel is reaching latte prices. Chat is this okay?\",\"url\":\"https://gizmodo.com/say-hello-to-6-diesel-2000810340\",\"urlToImage\":\"https://gizmodo.com/app/uploads/2026/04/trump-gestures-firing-gun-1200x675.jpg\",\"publishedAt\":\"2026-09-11T02:21:57Z\",\"content\":\"Cue another milestone in your favorite presidents forever war-youre-not-allowed-to-call-a-war in Iran! The average price of diesel across the country is now $6 a gallon, with no end to the trend in s… [+2070 chars]\"},{\"source\":{\"id\":null,\"name\":\"Gizmodo.com\"},\"author\":\"Matt Novak\",\"title\":\"Diesel Hits Record High as Trump’s Forever War Against Iran Grinds On\",\"description\":\"\\\"Summer is over. Peace didn't happen. The war is still going on.\\\"\",\"url\":\"https://gizmodo.com/diesel-hits-record-high-as-trumps-forever-war-against-iran-grinds-on-2000808763\",\"urlToImage\":\"https://gizmodo.com/app/uploads/2026/09/iran-wedding-child-death-1200x675.jpg\",\"publishedAt\":\"2026-09-08T22:07:31Z\",\"content\":\"Diesel hit a record high on Monday and the price of crude oil climbed higher Tuesday as it’s becoming more clear that President Donald Trump has started a war he can’t win with Iran. Those prices are… [+3787 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Reuters\",\"title\":\"Iran warns vessels violating Hormuz transit rules of fines, detention\",\"description\":\"Aug 24 (Reuters) - Iran has issued a warning that vessels violating its arrangements for transiting the Strait of Hormuz could face restrictions, including f...\",\"url\":\"https://www.yahoo.com/news/articles/iran-warns-vessels-violating-hormuz-072314650.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/880a8d0afc5b58422b08f39d5793b10042f1fa609162a19d4121c4c8c5830f77/lightyear_networkapi/resizefill_w800_h450%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2Fd7086e3f29a29698cbe3932331853dff.jpg\",\"publishedAt\":\"2026-08-24T07:38:05Z\",\"content\":\"Aug 24 (Reuters) - Iran has issued a warning that vessels violating its arrangements for transiting the Strait of Hormuz could face restrictions, including fines, detention, or confiscation, the Pers… [+829 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Eltaf Najafizada\",\"title\":\"Iran Says Strait of Hormuz Deal With Oman Just Days Away\",\"description\":\"Iran said a deal with Oman to manage shipping through the Strait of Hormuz is days away.\",\"url\":\"https://finance.yahoo.com/energy/articles/iran-says-strait-hormuz-deal-082152877.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/1d5c1965ec57f71d61b4535e65875fcf4a442add89132926809721f2d56b1ecf/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fbloomberg_holding_pen_162%2Fd00c7a6a2ed41b986a996939915b870a.jpg\",\"publishedAt\":\"2026-09-07T08:21:52Z\",\"content\":\"(Bloomberg) -- Iran said a deal with Oman to manage shipping through the Strait of Hormuz is days away.\\r\\nMost Read from Bloomberg\\r\\nThe agreement, which the two countries have been negotiating for wee… [+800 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":null,\"title\":\"New report of attack on Strait of Hormuz shipping fans fears of threats to oil supplies\",\"description\":null,\"url\":\"https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_a91a0a66-c913-4247-9888-f1d2d8dba437\",\"urlToImage\":null,\"publishedAt\":\"2026-09-13T02:22:41Z\",\"content\":\"If you click 'Accept all', we and our partners, including 252 who are part of the IAB Transparency &amp;amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Alex Longley, Julian Lee and Yongchang Chin\",\"title\":\"Hormuz Oil Flows Rising as Gulf Giants’ Ramp Up Accelerates\",\"description\":\"The flow of crude through the Strait of Hormuz is creeping higher as producers across the Middle East boost exports in the face of Iran’s lingering threat to...\",\"url\":\"https://finance.yahoo.com/energy/articles/hormuz-oil-flows-rising-gulf-130920932.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/0edd1b97dc860331b393c84cb7d205190a4d3255f671dfc3ef2fc534ac985f43/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fbloomberg_holding_pen_162%2F6f25ebd6f3abd9c1dda78a9e5402e941.jpg\",\"publishedAt\":\"2026-08-27T13:09:20Z\",\"content\":\"(Bloomberg) -- The flow of crude through the Strait of Hormuz is creeping higher as producers across the Middle East boost exports in the face of Iran's lingering threat to shipping. The increase is … [+5457 chars]\"},{\"source\":{\"id\":\"bbc-news\",\"name\":\"BBC News\"},\"author\":\"https://www.facebook.com/bbcnews\",\"title\":\"Satellite image reveals major damage that shut crucial oil pipeline\",\"description\":\"Experts tell BBC Verify the pipeline's closure could cut oil supplies by as much as 3.6 million barrels per day.\",\"url\":\"https://www.bbc.co.uk/news/articles/c65yw2gq2nrno\",\"urlToImage\":\"https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/6491/live/f14f3560-b10c-11f1-a540-61c3f7fc4e6c.png\",\"publishedAt\":\"2026-09-15T14:21:14Z\",\"content\":\"Satellite imagery shows a key oil pipeline in Saudi Arabia has been badly damaged after a strike last week, which experts have told BBC Verify could take more than a month to repair and force oil pri… [+1253 chars]\"},{\"source\":{\"id\":null,\"name\":\"Newsnationnow.com\"},\"author\":\"Tom Dempsey\",\"title\":\"Iran strikes Kuwait and Bahrain as Trump predicts Iran’s regime could fall\",\"description\":\"Six vessels transited the Strait of Hormuz Wednesday, down from 11 the day before, according to preliminary Kpler data.\",\"url\":\"https://www.newsnationnow.com/world/us-iran-war-strikes-kuwait-bahrain-strait-of-hormuz/\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/7bb9938be51903c9c8097a0158b0fa86336916d87fc88ea0681f4eacfcef0eb3/lightyear_networkapi/resizefill_w900_h506%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fnewsnation_articles_600%2Feba8e83456f293ec2a833e261d3d07d0.jpg\",\"publishedAt\":\"2026-09-03T10:53:28Z\",\"content\":\"(NewsNation) Israeli Defense Minister Israel Katz warned Thursday that if Iran attacks Israel, the country will target Iran's energy facilities as well as other military and civilian infrastructure.\\r… [+3585 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Reuters\",\"title\":\"Iran sets conditions for reopening Strait of Hormuz, top security official Rezaei says\",\"description\":\"Aug 27 (Reuters) - Iran is preparing a list of conditions for reopening the Strait of Hormuz after mediators asked Tehran to set them out, said Mohsen Rezaei...\",\"url\":\"https://www.yahoo.com/news/world/articles/iran-sets-conditions-reopening-strait-205036950.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/d94f8cec6def30a302772988012635a99ed2a2ccb933a0e70f0f9598b03ad6bc/lightyear_networkapi/resizefill_w800_h450%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F16f6814bde0cf7df52012b83f3ac7cf1.jpg\",\"publishedAt\":\"2026-08-27T20:50:36Z\",\"content\":\"Aug 27 (Reuters) - Iran is preparing a list of conditions for reopening the Strait of Hormuz after mediators asked Tehran to set them out, said Mohsen Rezaei, secretary of Iran's Supreme National Sec… [+1222 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Enas Alashray, Idrees Ali and Jana Choukeir\",\"title\":\"Iran and US hit tankers in biggest wave of attacks on shipping since war began\",\"description\":\"CAIRO/WASHINGTON/DUBAI, Sept 9 (Reuters) - Iran said on Wednesday it had attacked 10 ships near the Strait of Hormuz after the U. sank five Iranian oil tanke...\",\"url\":\"https://uk.news.yahoo.com/iran-attacks-us-jordan-ships-040647971.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/eda0ce87a34e301fbdbe220fa17146c694843000bc012114c20bc6c52277b00a/lightyear_networkapi/resizefill_w800_h422%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2Fc72cdb8511854fac7aecbbe8f186b6d1.jpg\",\"publishedAt\":\"2026-09-09T11:48:31Z\",\"content\":\"By Enas Alashray, Idrees Ali and Jana Choukeir\\r\\nCAIRO/WASHINGTON/DUBAI, Sept 9 (Reuters) - Iran said on Wednesday it had attacked 10 ships near the Strait of Hormuz after the U.S. sank five Iranian o… [+5602 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Yongchang Chin\",\"title\":\"Goldman Says Hormuz Oil Flows at Two-Thirds of Pre-War Levels\",\"description\":\"Oil flows through the Strait of Hormuz have recovered to around two-thirds of pre-war levels, limiting the Iran war's impact on global crude prices, accordin...\",\"url\":\"https://finance.yahoo.com/energy/articles/goldman-says-hormuz-oil-flows-012118583.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/81de3ce3ac149aaf827f95921b5d1aeef6a37a79032b00f43da17e7d0ef7d21d/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fbloomberg_holding_pen_162%2Fdcf05901a6e59b9ed36c80ed131def19.jpg\",\"publishedAt\":\"2026-08-28T01:21:18Z\",\"content\":\"(Bloomberg) -- Oil flows through the Strait of Hormuz have recovered to around two-thirds of pre-war levels, limiting the Iran war's impact on global crude prices, according to Goldman Sachs Group In… [+1432 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"SAMY MAGDY and CARA ANNA\",\"title\":\"An Iranian commercial ship is struck near Strait of Hormuz with 1 dead, Iranian media say\",\"description\":\"An Iranian commercial vessel was struck early Sunday off Qeshm Island in the Strait of Hormuz, with one person killed and four wounded, Iranian state media s...\",\"url\":\"https://www.yahoo.com/news/world/articles/iranian-commercial-ship-struck-near-055331558.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/b624d60a18c1595dc353c6c4d9032eccdb2b27b7b2d58fd16ea69a6f0cadf517/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fap.org%2Fb04ee160c39dc38175be25c64265305e.jpg\",\"publishedAt\":\"2026-09-13T05:53:31Z\",\"content\":\"CAIRO (AP) An Iranian commercial vessel was struck early Sunday off Qeshm Island in the Strait of Hormuz, with one person killed and four wounded, Iranian state media said, a day before Tehran seeks … [+2308 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Bingyan Wang\",\"title\":\"Oil Extends Gain as Iran Says Hormuz Deal With Oman Is Close\",\"description\":\"Oil extended gains as traders watched for details of an Iranian deal with Oman to manage shipping through the Strait of Hormuz, which could tighten Tehran’s...\",\"url\":\"https://finance.yahoo.com/energy/articles/oil-extends-gain-iran-says-220949793.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/7ede6d0b49d16b54293fe4f189526764c62988e25b939cf09238de5314c6f294/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fbloomberg_holding_pen_162%2Fe92b4730eb9c532c553ec4ecff4a055e.jpg\",\"publishedAt\":\"2026-09-07T22:09:49Z\",\"content\":\"(Bloomberg) -- Oil extended gains as traders watched for details of an Iranian deal with Oman to manage shipping through the Strait of Hormuz, which could tighten Tehran's control over the crucial wa… [+1368 chars]\"},{\"source\":{\"id\":null,\"name\":\"Abcnews.com\"},\"author\":\"David Brennan\",\"title\":\"Iran live updates: Oil prices rise after strikes in Saudi Arabia, Strait of Hormuz\",\"description\":\"The strategic Strait of Hormuz remains the conflict's primary flashpoint.\",\"url\":\"https://abcnews.com/International/live-updates/iran-live-updates-oil-prices-rise-after-strikes/?id=136415261\",\"urlToImage\":\"https://i.abcnewsfe.com/a/2291c521-787c-4434-b069-6fca212758d3/Saudi-pumping-station-DB-260914_1789369396568_hpMain_16x9.jpg?w=1600\",\"publishedAt\":\"2026-09-14T07:16:19Z\",\"content\":\"President Donald Trump on Sunday said global diesel shortages are not a result of the ongoing conflict in the Middle East, instead blaming Ukrainian strikes on Russian oil facilities and urging Ukrai… [+1285 chars]\"},{\"source\":{\"id\":\"bbc-news\",\"name\":\"BBC News\"},\"author\":\"https://www.facebook.com/bbcnews\",\"title\":\"How escalating Saudi oil crisis could drive up prices everywhere\",\"description\":\"BBC Verify's Ben Chu examines what impact rising energy costs could have on the global economy.\",\"url\":\"https://www.bbc.co.uk/news/articles/cqlym3wye1ero\",\"urlToImage\":\"https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/1a2a/live/d6d03600-b1e6-11f1-bc1f-3f186ca4140c.png\",\"publishedAt\":\"2026-09-16T16:06:50Z\",\"content\":\"Over the past two weeks, the Houthis in Yemen have captured strategic territory from Saudi-backed pro-government forces close to the Bab al-Mandab Strait, another trade chokepoint at the southern tip… [+1073 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Yomna Ehab\",\"title\":\"Iran and Oman discuss temporary Hormuz corridor as impasse with US drags on\",\"description\":\"CAIRO, Aug 26 (Reuters) - Iran said it had restarted talks with neighbor Oman to manage the Strait of Hormuz as it faces heightened economic pressure from U....\",\"url\":\"https://www.yahoo.com/news/politics/articles/iran-oman-discuss-temporary-hormuz-222048889.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/9562a8eec635c6bf68defad2c6a82c30b51fc84190b7d3639bb02fd2c26ca4cf/lightyear_networkapi/resizefill_w800_h450%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F2642651454b434a7455a39029aba2ceb.jpg\",\"publishedAt\":\"2026-08-25T22:47:06Z\",\"content\":\"By Yomna Ehab\\r\\nCAIRO, Aug 26 (Reuters) - Iran said it had restarted talks with neighbor Oman to manage the Strait of Hormuz as it faces heightened economic pressure from U.S. President Donald Trump i… [+2860 chars]\"},{\"source\":{\"id\":\"business-insider\",\"name\":\"Business Insider\"},\"author\":\"Jake Epstein,Chris Panella\",\"title\":\"Iran says it captured an 'advanced' American underwater drone. The US says it was older, malfunctioning, and ‘dead in the water.’\",\"description\":\"A spokesperson for US Central Command said the underwater drone had malfunctioned before Iran claimed to have seized it near the Strait of Hormuz.\",\"url\":\"https://www.businessinsider.com/iran-found-us-naval-drone-us-says-dead-in-water-2026-9\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/5906bf13bfb114e1899bb871e71bfc51f49f6af3f67831b97a4a5accc57c5146/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fbusiness_insider_consolidated_articles_886%2F76cff9ebcb8b238449866558b58a1fe5.jpg\",\"publishedAt\":\"2026-09-08T20:24:06Z\",\"content\":\"&lt;ul&gt;&lt;li&gt;Iran said it captured a US underwater drone near the Strait of Hormuz.\\r\\n&lt;/li&gt;&lt;li&gt;US Central Command said the older drone had malfunctioned and was \\\"dead in the water.\\\"\\r\\n&lt;/li&gt;&lt;li&gt;The US said i… [+2778 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"The Associated Press\",\"title\":\"US denies Iran's claim to have struck an unmanned ship, and other Mideast news\",\"description\":\"The U.S. military has denied Iran ’s claim to have struck an unmanned American military vessel in the Strait of Hormuz, calling it a “total lie.”  Meanwhile,...\",\"url\":\"https://www.yahoo.com/news/world/articles/iran-says-hit-us-ship-093513422.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/e83b7d73b594c4276e63f249af9a3b9422f41471ce9e5c3df2ee3eaf81fba56a/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fap.org%2F12043951bf997c9e6e73800aed228378.jpg\",\"publishedAt\":\"2026-09-06T09:35:13Z\",\"content\":\"The U.S. military has denied Iran 's claim to have struck an unmanned American military vessel in the Strait of Hormuz, calling it a \\\"total lie.\\\"\\r\\nMeanwhile, Israeli strikes in southern Lebanon kille… [+5650 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Colleen Howe\",\"title\":\"Oil prices jump more than $3 after new strikes on Saudi, Strait of Hormuz\",\"description\":\"By Colleen Howe BEIJING, Sept 14 (Reuters) - Oil prices jumped more than 2% on Monday, after new Houthi strikes on Saudi Arabia and Iranian attacks on ships...\",\"url\":\"https://finance.yahoo.com/energy/articles/oil-prices-jump-more-3-224715375.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/efccf5b8c3780dc1cf8a49b560c3187560ddbc971c77d9592af030edaaac992c/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F894db66e3536a8c890689797bdb5eff7.jpg\",\"publishedAt\":\"2026-09-13T22:47:15Z\",\"content\":\"By Colleen Howe\\r\\nBEIJING, Sept 14 (Reuters) - Oil prices jumped more than 2% on Monday, after new Houthi strikes on Saudi Arabia and Iranian attacks on ships in the Gulf compounded supply concerns fo… [+2257 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":null,\"title\":\"Iran says it captured US submarine drone in Strait of Hormuz\",\"description\":null,\"url\":\"https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_960bfb28-e3db-461a-9283-a9e5a8c7b81b\",\"urlToImage\":null,\"publishedAt\":\"2026-09-09T03:27:01Z\",\"content\":\"If you click 'Accept all', we and our partners, including 252 who are part of the IAB Transparency &amp;amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]\"},{\"source\":{\"id\":\"bbc-news\",\"name\":\"BBC News\"},\"author\":\"https://www.facebook.com/bbcnews\",\"title\":\"US diesel prices hit an all-time-high\",\"description\":\"Fuel prices have soared since the Iran conflict began at the end of February, mirroring the surge in wholesale oil prices.\",\"url\":\"https://www.bbc.co.uk/news/articles/c7903r0grx0o\",\"urlToImage\":\"https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/f9ea/live/aaff4f90-a843-11f1-b3a7-d5de760fef6e.jpg\",\"publishedAt\":\"2026-09-04T09:59:50Z\",\"content\":\"Drivers in the US are paying more than ever for diesel at the pump as the US-Israel war with Iran continues to hit Americans' wallets.\\r\\nThe average price for one gallon of diesel in the US has hit $5… [+2095 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Associated Press\",\"title\":\"Sultan of Oman to make state visit to UK, balancing pressures from US and Iran\",\"description\":\"The Sultan of Oman will visit Britain for a three-day state visit next month as the Arab nation that controls the southern shore of the Strait of Hormuz come...\",\"url\":\"https://www.yahoo.com/news/world/articles/sultan-oman-state-visit-uk-113623978.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/0611c09a2db8057ba7bea1af2d296c5561e5392c7863087c967525440448ea35/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fap.org%2F38311d508ca991ce95410764a7df4b83.jpg\",\"publishedAt\":\"2026-09-03T11:36:23Z\",\"content\":\"LONDON (AP) The Sultan of Oman will visit Britain for a three-day state visit next month as the Arab nation that controls the southern shore of the Strait of Hormuz comes under pressure from both the… [+1318 chars]\"},{\"source\":{\"id\":null,\"name\":\"Abcnews.com\"},\"author\":\"David Brennan\",\"title\":\"Iran live updates: CENTCOM says targeted Iranian forces posed 'imminent threat'\",\"description\":\"CENTCOM said it attacked \\\"minelaying forces\\\" in the Strait of Hormuz on Sunday.\",\"url\":\"https://abcnews.com/International/live-updates/iran-live-updates-centcom-targeted-iranian-forces-posed/?id=136080582\",\"urlToImage\":\"https://i.abcnewsfe.com/a/b45a12a1-c405-466d-aae9-9577839e189f/260830_wn_portnoy_iran_610_hpMain_16x9.jpg?w=1600\",\"publishedAt\":\"2026-08-31T06:09:23Z\",\"content\":\"United States forces on Sunday struck two Iranian rocket launch sites on Larak Island, according to a U.S. official.\\r\\nIRGC forces were observed to be preparing rockets armed with sea mines for launch… [+680 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"SAMY MAGDY and JULIA FRANKEL\",\"title\":\"Iran claims a strike on a US ship in the Strait of Hormuz but the US denies it\",\"description\":\"Iran said Sunday it struck an unmanned U.S. vessel trying to enter the Strait of Hormuz, a claim that the U.S. military dismissed as a “total lie.”  The purp...\",\"url\":\"https://www.yahoo.com/news/world/articles/iran-claims-strike-us-ship-070335650.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/90134f3c6d4543cdd0cb7cec8a6dc90bed4ca52f7aa5aedea2f72ed9e4c15112/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fap.org%2F25b030f36e4e3a28922fc522a948ada5.jpg\",\"publishedAt\":\"2026-09-06T07:03:35Z\",\"content\":\"CAIRO (AP) Iran said Sunday it struck an unmanned U.S. vessel trying to enter the Strait of Hormuz, a claim that the U.S. military dismissed as a \\\"total lie.\\\"\\r\\nThe purported attack came a day after t… [+2973 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":null,\"title\":\"60 targets struck, 18M barrels of oil protected: The US military’s record day in the Strait of Hormuz\",\"description\":null,\"url\":\"https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_82b6cdab-123e-454d-a2e0-d3fea8d02c91\",\"urlToImage\":null,\"publishedAt\":\"2026-09-02T23:25:35Z\",\"content\":\"If you click 'Accept all', we and our partners, including 251 who are part of the IAB Transparency &amp;amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]\"},{\"source\":{\"id\":null,\"name\":\"NPR\"},\"author\":\"The Associated Press\",\"title\":\"Iran-backed Houthi rebels seize strategic Red Sea port in Yemen\",\"description\":\"The rebel group took over Yemen's port of Mokha, an area vital to controlling shipping through the Red Sea, Houthi and Yemeni officials said. Mokha is about 50 miles from the Bab el-Mandeb Strait.\",\"url\":\"https://www.npr.org/2026/09/11/g-s1-142822/houthis-red-sea-port\",\"urlToImage\":\"https://npr.brightspotcdn.com/dims3/default/strip/false/crop/6618x3723+0+345/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F97%2F26%2F70548b854bb7801d39d7d604b02f%2Fap26253317964125.jpg\",\"publishedAt\":\"2026-09-11T05:40:21Z\",\"content\":\"ADEN, Yemen The Iran-backed Houthi rebel group on Thursday took over Yemen's port city of Mokha, an area vital to controlling shipping through the Red Sea, Houthi and Yemeni officials said.\\r\\nThe take… [+6227 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Samia Nakhoul\",\"title\":\"Analysis-Iran's Hormuz leverage wanes as US economic squeeze bites\",\"description\":\"By Samia Nakhoul ISTANBUL, Sept 6 (Reuters) - Six months after a conflict that rattled markets and pushed the Gulf to the brink of a wider war, the tide may...\",\"url\":\"https://www.yahoo.com/news/articles/analysis-irans-hormuz-leverage-wanes-124818005.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/99b2edb8be3076191765c86fd427df9a3aeb8149c991834eb0078d283b51acf3/lightyear_networkapi/resizefill_w800_h533%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F0ee3544e7b52155986e84e3afb7e86e3.jpg\",\"publishedAt\":\"2026-09-06T12:48:18Z\",\"content\":\"By Samia Nakhoul\\r\\nISTANBUL, Sept 6 (Reuters) - Six months after a conflict that rattled markets and pushed the Gulf to the brink of a wider war, the tide may be turning against Iran as Washington unl… [+5807 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"FATMA KHALED and CARA ANNA\",\"title\":\"Iran seeks end to Saudi blockade of Yemen after Tehran-backed rebels take key port\",\"description\":\"Iran's government on Friday called for an end to Saudi Arabia's blockade of Yemen and the immediate resumption of talks, in its first public statement since...\",\"url\":\"https://www.yahoo.com/news/world/articles/iran-seeks-end-saudi-blockade-072820876.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/335c70d15cfc16bf55ae490633ecacc6997e6c2cca0c778d19140afe6e697e73/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fap.org%2Fa6f1f6153f7700a1b4acfb02ac096f4d.jpg\",\"publishedAt\":\"2026-09-11T07:28:20Z\",\"content\":\"CAIRO (AP) Iran's government on Friday called for an end to Saudi Arabia's blockade of Yemen and the immediate resumption of talks, in its first public statement since Iran-backed Houthi rebels enter… [+2989 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"The Associated Press\",\"title\":\"Iran's president says Iran would return to ceasefire agreement if US does, and other Mideast news\",\"description\":\"Iran is ready to return to the ceasefire deal reached with the United States in June if Washington does the same, President Masoud Pezeshkian said on Tuesday...\",\"url\":\"https://www.yahoo.com/news/world/articles/irans-president-says-iran-return-093502284.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/675ca55e105d996dabef33b812899ba3b9603e727d4fa16f9f27cc47b5685a96/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fap.org%2Fa3ffcf681324f2329ab3f2c529ad7239.jpg\",\"publishedAt\":\"2026-09-01T09:35:02Z\",\"content\":\"Iran is ready to return to the ceasefire deal reached with the United States in June if Washington does the same, President Masoud Pezeshkian said on Tuesday, in conciliatory remarks following the fi… [+5865 chars]\"},{\"source\":{\"id\":null,\"name\":\"Abcnews.com\"},\"author\":\"David Brennan\",\"title\":\"Iran live updates: Tehran plans new 'restricted zone' outside Strait of Hormuz\",\"description\":\"A senior Iranian official said ships violating the new zone would be sanctioned.\",\"url\":\"https://abcnews.com/International/live-updates/iran-live-updates-tehran-plans-new-restricted-zone/?id=136249116\",\"urlToImage\":\"https://i.abcnewsfe.com/a/c427ba3f-fd25-4b5b-b162-c982072bf3e9/Hormuz-DB-260907_1788767662575_hpMain_16x9.jpg?w=1600\",\"publishedAt\":\"2026-09-07T08:06:26Z\",\"content\":\"Mohsen Rezaei, the secretary of Iran's Supreme National Security Council, said on Sunday that a restricted zone will be announced in the coming days \\\"outside\\\" the Strait of Hormuz, in comments carrie… [+515 chars]\"},{\"source\":{\"id\":\"cnn\",\"name\":\"CNN\"},\"author\":\"Analysis by Nadeen Ebrahim, CNN\",\"title\":\"The US wants to manage the stalemate in the Strait of Hormuz. Iran wants to break it\",\"description\":\"A monthlong lull in fighting between Iran and the US ended this week, dragging the region back to a dangerous – and potentially unsustainable – military stal...\",\"url\":\"https://www.cnn.com/2026/09/04/middleeast/us-iran-strait-of-hormuz-stalemate-intl\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/a35ea9a490db3e2f184d1587d9d2cb42eb8e199136d9822d6ce240c7b051041d/lightyear_networkapi/resizefill_w960_h540%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fcnn_articles_875%2F5c7bf4bbe71a1d9b9b688113eca03e49.jpg\",\"publishedAt\":\"2026-09-04T13:11:08Z\",\"content\":\"The monthlong lull in fighting between Iran and the United States ended this week with a renewed exchange of fire, dragging the region back to a dangerous and potentially unsustainable military stale… [+7908 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":null,\"title\":\"US forces strike Iranian rocket launchers on the Strait of Hormuz in first military action in weeks\",\"description\":null,\"url\":\"https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_f3a10201-e726-48b8-9068-28874c086ba8\",\"urlToImage\":null,\"publishedAt\":\"2026-08-30T20:01:34Z\",\"content\":\"If you click 'Accept all', we and our partners, including 251 who are part of the IAB Transparency &amp;amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Jason Ma\",\"title\":\"Oil prices dive on signs of Hormuz diplomacy while Saudi Arabia is left hanging in fight against an Iranian ally threatening crude’s other chokepoint\",\"description\":\"Foreign ministers from the Gulf Cooperation Council—which is comprised of Saudi Arabia, the UAE, Qatar, Kuwait, Bahrain, and Oman—will meet their Iranian cou...\",\"url\":\"https://finance.yahoo.com/energy/articles/oil-prices-dive-signs-hormuz-190707648.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/9094a15e890ac4381c19a4d6f46797eb8685cd42f2c1365b2e3ac28140f3676e/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Ffortune_175%2F9bd535cdb121e6cf176ccf40502c7558.jpg\",\"publishedAt\":\"2026-09-11T19:07:07Z\",\"content\":\"After weeks when Middle East diplomacy seemed dead in the water, a rare meeting between Iran and its Persian Gulf neighbors has renewed hope for a deal that could fully reopen the Strait of Hormuz.\\r\\n… [+3782 chars]\"},{\"source\":{\"id\":null,\"name\":\"Abcnews.com\"},\"author\":\"Zunaira Zaki, David Brennan\",\"title\":\"Diesel prices at record highs amid Strait of Hormuz disruption, Russia-Ukraine war\",\"description\":\"The average price for a gallon of diesel was still hovering around a record-high of $6.43 as of Friday morning, according to the latest data published by GasBuddy.\",\"url\":\"https://abcnews.com/Business/diesel-prices-record-highs-amid-strait-hormuz-disruption/story?id=136552505\",\"urlToImage\":\"https://i.abcnewsfe.com/a/5d87eac4-76f4-4cfc-9a1e-41a3c4d6f506/Diesel-prices-DB-260918_1789727552275_hpMain_16x9.jpg?w=1600\",\"publishedAt\":\"2026-09-18T10:42:40Z\",\"content\":\"The average price for a gallon of diesel was still hovering around a record-high of $6.43 as of Friday morning, according to the latest data published by GasBuddy.\\r\\nThis is a developing story. Please… [+23 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Florence Tan\",\"title\":\"Oil extends gains after US and Iran strike ships\",\"description\":\"By Florence Tan SINGAPORE, Sept 7 (Reuters) - Oil prices extended gains on Monday as tit-for-tat strikes between the U.S. and Iran on vessels sailing in the...\",\"url\":\"https://finance.yahoo.com/energy/articles/oil-extends-gains-us-iran-001532615.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/3604d7e642f90d6f92923fe33720802d6ed0338a9c76c194a9986cdca6ad28ae/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F2f13607cd1bad7569c2d018dab33176b.jpg\",\"publishedAt\":\"2026-09-07T00:15:32Z\",\"content\":\"By Florence Tan\\r\\nSINGAPORE, Sept 7 (Reuters) - Oil prices extended gains on Monday as tit-for-tat strikes between the U.S. and Iran on vessels sailing in the Strait of Hormuz and other areas heighten… [+2266 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Kanishka Singh\",\"title\":\"US military says it completed latest wave of strikes on Iran\",\"description\":\"By Kanishka Singh WASHINGTON, Sept 1 (Reuters) - The U.S. military said late on Tuesday it completed its latest wave of strikes on Iran, saying it struck Isl...\",\"url\":\"https://uk.news.yahoo.com/us-military-says-completed-latest-015610435.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/6f487fc8d5d3dad6fc397951c94721e25755e1111becfd3bca94371ee9d0728a/lightyear_networkapi/resizefill_w800_h450%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F7bc1d171933a3d70bf2dda1cb17395c8.jpg\",\"publishedAt\":\"2026-09-02T01:56:10Z\",\"content\":\"By Kanishka Singh\\r\\nWASHINGTON, Sept 1 (Reuters) - The U.S. military said late on Tuesday it completed its latest wave of strikes on Iran, saying it struck Islamic Revolutionary Guard Corps targets as… [+1883 chars]\"},{\"source\":{\"id\":null,\"name\":\"Gizmodo.com\"},\"author\":\"Matt Novak\",\"title\":\"Are Truckers Really Going on Strike Oct. 1?\",\"description\":\"There's a lot of chatter online, but is it just talk?\",\"url\":\"https://gizmodo.com/are-truckers-really-going-on-strike-oct-1-2000813490\",\"urlToImage\":\"https://gizmodo.com/app/uploads/2026/09/are-truckers-striking-october-1-1200x675.jpg\",\"publishedAt\":\"2026-09-18T13:25:18Z\",\"content\":\"A video went viral on Instagram Thursday claiming that truckers in the U.S. were going on strike starting Oct. 1 to protest the price of diesel, which has skyrocketed to a national average of $6.39 p… [+6687 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Ari Natter and Annmarie Hordern\",\"title\":\"Oil Pipe Bypassing Hormuz to Reopen ‘Soon,’ US Energy Chief Says\",\"description\":\"A critical Saudi oil pipeline should be back online “soon” following it’s closure late last week after coming under attack, Energy Secretary Chris Wright sai...\",\"url\":\"https://finance.yahoo.com/energy/articles/oil-pipe-bypassing-hormuz-reopen-130220980.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/2f343311a267a4486f919cf6764a3f9e2abb2767ff385335e3ccba0fd9c7a31f/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fbloomberg_holding_pen_162%2F5bba858df76fab63a5f2a0ded781e166.jpg\",\"publishedAt\":\"2026-09-14T13:02:20Z\",\"content\":\"(Bloomberg) -- A critical Saudi oil pipeline should be back online \\\"soon\\\" following it's closure late last week after coming under attack, Energy Secretary Chris Wright said Monday.\\r\\nMost Read from B… [+608 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"Reuters\",\"title\":\"Explainer-What are Iran's options to escalate further in face of US economic threats?\",\"description\":\"LONDON, Aug 24 - U.S. threats to impose \\\"the toughest sanctions in history\\\" to force Iran to buckle to its demands after nearly six months of war have raised...\",\"url\":\"https://www.yahoo.com/news/articles/explainer-irans-options-escalate-further-153341041.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/f5937d6e922b626eb6a6784b37284b5352c15285a5fe4a0c8fad9780ea84822f/lightyear_networkapi/resizefill_w800_h533%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F7f3ea7b42a31bddcc674a0f19e84975d.jpg\",\"publishedAt\":\"2026-08-24T15:33:41Z\",\"content\":\"LONDON, Aug 24 - U.S. threats to impose \\\"the toughest sanctions in history\\\" to force Iran to buckle to its demands after nearly six months of war have raised the prospect of a new round of escalation… [+3238 chars]\"},{\"source\":{\"id\":\"cnn\",\"name\":\"CNN\"},\"author\":\"Analysis by Mostafa Salem and Aida Karimi, CNN\",\"title\":\"Trump’s blockade pushes Iran toward military escalation\",\"description\":\"As Washington abandons talks with Iran for an aggressive economic pressure campaign, a cornered Tehran is now threatening military escalation and a wider war...\",\"url\":\"https://www.cnn.com/2026/09/07/middleeast/trump-blockade-iran-military-escalation-intl-latam\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/a46dbe6e8b3377f7cec5bc8656bceab28543370a7b7d6b0e24c930a32f888977/lightyear_networkapi/resizefill_w960_h540%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Fcnn_articles_875%2Fab1120fde7212c8abc6fce89ec7af2c8.jpg\",\"publishedAt\":\"2026-09-07T17:19:23Z\",\"content\":\"As Washington abandons talks with Iran for an aggressive economic pressure campaign, a cornered Tehran is now threatening military escalation and a wider war to force negotiators back to the table.\\r\\n… [+7919 chars]\"},{\"source\":{\"id\":null,\"name\":\"Yahoo Entertainment\"},\"author\":\"By Phil Stewart and David Lawder\",\"title\":\"Trump says Iran's Kharg is being 'blown to smithereens', but gives no details\",\"description\":\"WASHINGTON, Aug 30 (Reuters) - Iran's energy hub of Kharg Island is being blown to smithereens, U. President Donald Trump said on Sunday in a one-line social...\",\"url\":\"https://uk.news.yahoo.com/us-iran-exchange-fire-flare-021359484.html\",\"urlToImage\":\"https://s.yimg.com/lo/mysterio/api/a2a1b3ba75629c64b1c27e6e051e75e234a9ccbaa716511720eab230a37ea17b/lightyear_networkapi/resizefill_w800_h533%3Bquality_80%3Bformat_jpg/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Freuters.com%2F46ae2709c2c5e172296ff7f0915bfc3e.jpg\",\"publishedAt\":\"2026-08-31T03:29:40Z\",\"content\":\"By Phil Stewart and David Lawder\\r\\nWASHINGTON, Aug 30 (Reuters) - Iran's energy hub of Kharg Island is being blown to smithereens, U.S. President Donald Trump said on Sunday in a one-line social media… [+4521 chars]\"}]}"</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>We then parse what is returned and find our way to the data frame that has the actual article information in it (check content).</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>raw_text <span class="ot">&lt;-</span> <span class="fu">content</span>(news_result, <span class="at">as =</span> <span class="st">"text"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>parsed_json <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(raw_text)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(parsed_json, <span class="at">max.level =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ status      : chr "ok"
 $ totalResults: int 6450
 $ articles    :'data.frame':   50 obs. of  8 variables:</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>articles_df <span class="ot">&lt;-</span> parsed_json<span class="sc">$</span>articles</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(articles_df)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="3" type="1">
<li>We write a quick function that allows the user to easily query this API. The inputs to the function are the title/subject to search for, a time period to search from, and an API key.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>get_info <span class="ot">&lt;-</span> <span class="cf">function</span>(query, from_date, api_key) {</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  response <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="st">"https://newsapi.org/v2/everything"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">query =</span> <span class="fu">list</span>(<span class="at">q =</span> query,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">from =</span> from_date,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">language =</span> <span class="st">"en"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">pageSize =</span> <span class="dv">50</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">apiKey =</span> api_key))</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  parsed <span class="ot">&lt;-</span> <span class="fu">content</span>(response, <span class="at">as =</span> <span class="st">"parsed"</span>, <span class="at">simplifyDataFrame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (parsed<span class="sc">$</span>status <span class="sc">!=</span> <span class="st">"ok"</span>) {</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"NewsAPI request failed: "</span>, parsed<span class="sc">$</span>message)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(parsed<span class="sc">$</span>articles)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>Hormuz_news <span class="ot">&lt;-</span> <span class="fu">get_info</span>(<span class="st">"Strait of Hormuz"</span>, from_date, api_key)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>Hormuz_news</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 bbc-news  BBC … https… Saud… The East-W… http… https://i… 2026-09-12… "Saudi…
 2 bbc-news  BBC … https… US l… US Central… http… https://i… 2026-09-01… "Ameri…
 3 &lt;NA&gt;      Gizm… Matt … Trum… Trump says… http… https://g… 2026-09-16… "The F…
 4 business… Busi… Jake … Iran… A spokespe… http… https://i… 2026-09-08… "US Ce…
 5 &lt;NA&gt;      Yaho… By Fl… Two … By Florenc… http… https://s… 2026-09-01… "By Fl…
 6 &lt;NA&gt;      Yaho… By El… Iran… DUBAI/CAIR… http… https://s… 2026-08-28… "By El…
 7 &lt;NA&gt;      Yaho… &lt;NA&gt;   Ship… &lt;NA&gt;        http… &lt;NA&gt;       2026-08-27… "If yo…
 8 bbc-news  BBC … https… Ligh… The captur… http… https://i… 2026-09-11… "\"Now…
 9 &lt;NA&gt;      NPR   Jane … Atta… U.S. threa… http… https://n… 2026-08-31… "AMMAN…
10 &lt;NA&gt;      Gizm… Tom M… Say … Diesel is … http… https://g… 2026-09-11… "Cue a…
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>Calling function on a different topic to check if it really works. This time the topic is the FDA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>get_info <span class="ot">&lt;-</span> <span class="cf">function</span>(query, from_date, api_key) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  response <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="st">"https://newsapi.org/v2/everything"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">query =</span> <span class="fu">list</span>(<span class="at">q =</span> query,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">from =</span> from_date,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">language =</span> <span class="st">"en"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">pageSize =</span> <span class="dv">50</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">apiKey =</span> api_key))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  parsed <span class="ot">&lt;-</span> <span class="fu">content</span>(response, <span class="at">as =</span> <span class="st">"parsed"</span>, <span class="at">simplifyDataFrame =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (parsed<span class="sc">$</span>status <span class="sc">!=</span> <span class="st">"ok"</span>) {</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"NewsAPI request failed: "</span>, parsed<span class="sc">$</span>message)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(parsed<span class="sc">$</span>articles)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>fda_news <span class="ot">&lt;-</span> <span class="fu">get_info</span>(<span class="st">"FDA"</span>, from_date, api_key)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>fda_news</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 8
   source$id $name author title description url   urlToImage publishedAt content
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;  
 1 the-verge The … Andre… Circ… "Circular … http… https://p… 2026-09-03… "&lt;ul&gt;&lt;…
 2 &lt;NA&gt;      Gizm… Ed Ca… A Ga… "In a larg… http… https://g… 2026-08-26… "An ex…
 3 &lt;NA&gt;      Gizm… Matt … Epin… "\"Particu… http… https://g… 2026-09-04… "Pharm…
 4 &lt;NA&gt;      Yaho… NBC    FDA … "Closing a… http… https://s… 2026-08-27… "Closi…
 5 &lt;NA&gt;      Slas… BeauHD FDA … "The FDA h… http… https://a… 2026-08-24… "Preci…
 6 &lt;NA&gt;      Yaho… &lt;NA&gt;   Roch…  &lt;NA&gt;       http… &lt;NA&gt;       2026-08-24… "If yo…
 7 &lt;NA&gt;      News… Zach … Thyr… "Patients … http… https://s… 2026-08-25… "(News…
 8 &lt;NA&gt;      Yaho… By Em… Altr… "By Emma R… http… https://s… 2026-09-02… "By Em…
 9 usa-today USA … Ken A… Eli … "The FDA a… http… https://s… 2026-08-28… "The F…
10 &lt;NA&gt;      Abcn… Ava T… FDA … "Specialis… http… https://i… 2026-09-18… "Testo…
# ℹ 40 more rows</code></pre>
</div>
</div>
</section>
<section id="task-2---summarizing-roller-coaster-data" class="level2">
<h2 class="anchored" data-anchor-id="task-2---summarizing-roller-coaster-data">Task 2 - Summarizing Roller Coaster Data</h2>
<section id="read-and-prepare-the-data" class="level3">
<h3 class="anchored" data-anchor-id="read-and-prepare-the-data">Read and Prepare the Data</h3>
<p>I read in the roller coaster data and convert the categorical variables to factors. The data is sourced from the following link : https://www4.stat.ncsu.edu/online/datasets/635USrollercoasters.csv</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>coasters <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/online/datasets/635USrollercoasters.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 635 Columns: 21
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): Coaster, Park, City, State, Census Region, AgeGroup, Scale, Type, ...
dbl  (9): Year Opened, TopSpeed, MaxHeight, Drop, Length, Duration, # of Inv...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#glimpse(coasters)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># trying to figure out which columns make good factors </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span> coasters <span class="sc">|&gt;</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">n_distinct</span>(Coaster), <span class="fu">n_distinct</span>(Park), <span class="fu">n_distinct</span>(City), </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">n_distinct</span>(State), <span class="fu">n_distinct</span>(Make),<span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Census Region</span><span class="st">`</span>),</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">n_distinct</span>(AgeGroup),<span class="fu">n_distinct</span>(Scale), <span class="fu">n_distinct</span>(Type), </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">n_distinct</span>(Design), <span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>))</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 11
  `n_distinct(Coaster)` `n_distinct(Park)` `n_distinct(City)`
                  &lt;int&gt;              &lt;int&gt;              &lt;int&gt;
1                   482                197                171
# ℹ 8 more variables: `n_distinct(State)` &lt;int&gt;, `n_distinct(Make)` &lt;int&gt;,
#   `n_distinct(\`Census Region\`)` &lt;int&gt;, `n_distinct(AgeGroup)` &lt;int&gt;,
#   `n_distinct(Scale)` &lt;int&gt;, `n_distinct(Type)` &lt;int&gt;,
#   `n_distinct(Design)` &lt;int&gt;, `n_distinct(\`Inversions?\`)` &lt;int&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># checking the unique characters in agegroup and type </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(coasters<span class="sc">$</span>AgeGroup)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "3:Newest" "2:Recent" "1:Older" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(coasters<span class="sc">$</span>Type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Steel" "Wood" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># checking for nas or spaces </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(coasters<span class="sc">$</span>AgeGroup))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(coasters<span class="sc">$</span>Type))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>AgeGroup)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1:Older 2:Recent 3:Newest 
      69      190      376 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>Type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Steel  Wood 
  530   105 </code></pre>
</div>
</div>
<p>I think that the Factors are: State, Make, Census Region, AgeGroup, Scale, Type, Design, Inversions. The Not factors have too many unique values, and end up acting like identifiers those are: Coaster, Park, City.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>coasters <span class="ot">&lt;-</span> coasters <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(State, Make, <span class="st">`</span><span class="at">Census Region</span><span class="st">`</span>, AgeGroup, Scale, Type, Design, <span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>), </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                as.factor))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co">#str(coasters)</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co"># checking for missing values across every column:</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(coasters))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Coaster            Park            City           State   Census Region 
              0               0               0               0               0 
    Year Opened        AgeGroup        TopSpeed       MaxHeight           Scale 
              0               0              74               8               0 
           Type          Design            Drop          Length        Duration 
              0               0             128              33              66 
    Inversions? # of Inversions            Make        Latitude       Longitude 
              0               0              36               0               0 
       Boundary 
              0 </code></pre>
</div>
</div>
<p>Checking the Nas showed us that physical measurement fields which include columns Drop, TopSpeed, Duration, MaxHeight have real gaps. They had many Na values this is probably the information wasn’t available for some coasters. the column Drop has the most missing values by far.</p>
<p>Now we want to creat a one-way contingency table, a two-way contingency table, and a three-way contingency table for variablels type, inversion and scale. this is because i am intrested in seeing if the wood roller costers will have less inversions. The type will show how complex the roller coster is so it will be intresting to see the trend.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># one way table :</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>Scale)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Extreme  Family  Kiddie  Thrill 
    269     178      28     160 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># two way table :</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>Type, coasters<span class="sc">$</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
         No Yes
  Steel 364 166
  Wood  101   4</code></pre>
</div>
</div>
<p>From the two way table we see that out of the 105 wood coasters in the dataset, only 4 have inversions, compared to 166 out of 530 steel coasters, suggesting wood coaster designs are less likely to include inversions than steel ones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three way table :</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coasters<span class="sc">$</span>Type, coasters<span class="sc">$</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>, coasters<span class="sc">$</span>Scale)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = Extreme

       
         No Yes
  Steel  50 166
  Wood   49   4

, ,  = Family

       
         No Yes
  Steel 163   0
  Wood   15   0

, ,  = Kiddie

       
         No Yes
  Steel  27   0
  Wood    1   0

, ,  = Thrill

       
         No Yes
  Steel 124   0
  Wood   36   0</code></pre>
</div>
</div>
<p>looking at the two way table i found that in the Extreme scale slice, 166 out of 216 steel Extreme coasters have inversions, compared to only 4 out of 53 wood Extreme coasters. which proves what the two way table showed. Suprisingly however no coasters in the Family, Kiddie, or Thrill categories have any inversions at allsu. This might mean that inversions are a defining feature specifically of Extreme-scale rides. This is cool because i did not expect that to be the case</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 1 </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>extreme_only <span class="ot">&lt;-</span> coasters <span class="sc">|&gt;</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Scale <span class="sc">==</span> <span class="st">"Extreme"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(extreme_only<span class="sc">$</span>Type, extreme_only<span class="sc">$</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
         No Yes
  Steel  50 166
  Wood   49   4</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 2 </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>full_table <span class="ot">&lt;-</span> <span class="fu">table</span>(coasters<span class="sc">$</span>Type, coasters<span class="sc">$</span><span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>, coasters<span class="sc">$</span>Scale)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>full_table[, , <span class="st">"Extreme"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
         No Yes
  Steel  50 166
  Wood   49   4</code></pre>
</div>
</div>
<p>Step 1 : Group and count</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>counts_long <span class="ot">&lt;-</span> coasters <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Type, <span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Type'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>counts_long</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   Type [2]
  Type  `Inversions?`     n
  &lt;fct&gt; &lt;fct&gt;         &lt;int&gt;
1 Steel No              364
2 Steel Yes             166
3 Wood  No              101
4 Wood  Yes               4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>counts_long <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>, <span class="at">values_from =</span> n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
# Groups:   Type [2]
  Type     No   Yes
  &lt;fct&gt; &lt;int&gt; &lt;int&gt;
1 Steel   364   166
2 Wood    101     4</code></pre>
</div>
</div>
<p>Graphing</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coasters, <span class="fu">aes</span>(<span class="at">x =</span> Type, <span class="at">fill =</span> <span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Roller Coaster Inversions by Type (Stacked)"</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Coaster Type"</span>,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Maab_C_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coasters, <span class="fu">aes</span>(<span class="at">x =</span> Type, <span class="at">fill =</span> <span class="st">`</span><span class="at">Inversions?</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Roller Coaster Inversions by Type (Side-by-Side)"</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Coaster Type"</span>,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Maab_C_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our findings :</p>
<p>Overall we found that inversions are strongly tied to both coaster type and ride intensity. Steel coasters are considerably more likely to include inversions than Wood coasters, and notably, every coaster with inversions in the dataset falls under the “Extreme” scale category, with none present among Family, Kiddie, or Thrill rides. This suggests that inversions are less a general design feature and more a defining characteristic of the most intense, steel-built coasters.The side-by-side and a stacked bar graph comparing coaster type and inversion status, both visually confirmed that inversions are far more common among Steel coasters than Wood coasters.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>